### ISSUE TITLE
File formats and ConfigParser

### ISSUE THREAD

**Issue by briglo** [igm-team/orion-public#1]
Greetings

I was hoping to run Orion over some data that i have but when i fire up Orion (i first inferred from the use of ConfigParser that this is for python 2.7) i get the following TraceBack:
Traceback (most recent call last):
  File "path/to/briglo/gitrepos/orion-public/src/Orion.py", line 11, in <module>
    from OrionGlobals import *
  File "path/to/briglo/gitrepos/orion-public/src/OrionGlobals.py", line 25, in <module>
    boundaries_regex = re.compile(cfg.get("atav", "boundaries"))
  File "/opt/python/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'atav'

i found atav on your git but i am not sure how to get them to talk to each other

can you help me out? sorry if it's a simple issue

**Comment by gussow** [comment]
Hi @briglo 

I think the error you received was due to the accidental inclusion of some code in OrionGlobals that is not relevant anymore. I removed the offending code, please let me know if it works. Thanks for bringing this to our attention.

Ayal

**Comment by briglo** [comment]
Thanks Ayal,
I appreciate the help you are giving me
B
